server.servlet.context-path=/api
reqres.base-url=https://reqres.in
reqres.token=${REQRES_AUTH_TOKEN}
visualcrossing.api.base-url=https://weather.visualcrossing.com
visualcrossing.api.key=${VISUAL_CROSSING_TOKEN}